// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SynthBoardCollab.Models;

#nullable disable

namespace Synthboard.Migrations
{
    [DbContext(typeof(SynthContext))]
    partial class SynthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SynthBoardCollab.Models.Board", b =>
                {
                    b.Property<int>("BoardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomSound")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("BoardID");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("SynthBoardCollab.Models.SoundFile", b =>
                {
                    b.Property<int>("SoundFileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BaseSound")
                        .HasColumnType("longtext");

                    b.Property<int?>("BoardID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SoundFileID");

                    b.HasIndex("BoardID");

                    b.ToTable("SoundFile");
                });

            modelBuilder.Entity("SynthBoardCollab.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SynthBoardCollab.Models.SoundFile", b =>
                {
                    b.HasOne("SynthBoardCollab.Models.Board", "Board")
                        .WithMany("CustomSounds")
                        .HasForeignKey("BoardID");

                    b.Navigation("Board");
                });

            modelBuilder.Entity("SynthBoardCollab.Models.Board", b =>
                {
                    b.Navigation("CustomSounds");
                });
#pragma warning restore 612, 618
        }
    }
}
